export const COLUMNS = [
  { id: 'organization', label: 'Organization', minWidth: 40 },
  { id: 'projectName', label: 'Project Name', minWidth: 40 },
  { id: 'projectNumber', label: 'Project Number', minWidth: 40 },
  { id: 'projectManager', label: 'Project Manager', minWidth: 40 },
  { id: 'projectSupervisor', label: 'Project Supervisor', minWidth: 40 },
  { id: 'metaSystemName', label: 'System Name', minWidth: 40 },
  { id: 'equipmentCategory', label: 'Equipment Category', minWidth: 40 },
  { id: 'equipmentName', label: 'Equipment Name', minWidth: 40 },
  { id: 'equipmentNumber', label: 'Equipment Number', minWidth: 40 },
  { id: 'deliverableName', label: 'Deliverable Name', minWidth: 40 },
  { id: 'plannedHours', label: 'Planned hours', minWidth: 40 },
  { id: 'workedHours', label: 'Worked Hours', minWidth: 40 },
  { id: 'start', label: 'Start', minWidth: 40 },
  { id: 'end', label: 'End', minWidth: 40 },
  { id: 'status', label: 'Status', minWidth: 40 },
  { id: 'duration', label: 'Duration', minWidth: 40 },
  { id: 'remainingDays', label: 'Remaining Days', minWidth: 40 },
  { id: 'lapsed', label: 'Lapsed', minWidth: 40 },
  { id: 'differential', label: 'Differential', minWidth: 40 },
  { id: 'effort', label: 'Effort', minWidth: 40 },
  { id: 'eV', label: 'EV', minWidth: 40 },
  { id: 'pV', label: 'PV', minWidth: 40 },
];

export const HEADERS = [
  { label: 'Organization', key: 'organizationName' },
  { label: 'Project Name', key: 'projectName' },
  { label: 'Project Number', key: 'projectNumber' },
  { label: 'Project Manager', key: 'projectManager' },
  { label: 'Project Supervisor', key: 'projectSupervisor' },
  { label: 'System Name', key: 'metaSystemName' },
  { label: 'Equipment Category', key: 'equipmentCategory' },
  { label: 'Equipment Name', key: 'equipmentName' },
  { label: 'Equipment Number', key: 'equipmentNumber' },
  { label: 'Deliverable Name', key: 'deliverableName' },
  { label: 'Planned hours', key: 'plannedHours' },
  { label: 'Worked Hours', key: 'workedHours' },
  { label: 'Start', key: 'start' },
  { label: 'End', key: 'end' },
  { label: 'Status', key: 'status' },
  { label: 'Duration', key: 'calculated.duration' },
  { label: 'Remaining Days', key: 'calculated.remainingDays' },
  { label: 'Lapsed', key: 'calculated.lapsed' },
  { label: 'Differential', key: 'calculated.differential' },
  { label: 'Effort', key: 'calculated.effort' },
  { label: 'EV', key: 'calculated.EV' },
  { label: 'PV', key: 'calculated.PV' },
];
