const SET_CURRENT_USER = 'SET_CURRENT_USER';
const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN';
const SET_PASSWORD_RESET_TOKEN = 'SET_PASSWORD_RESET_TOKEN';
const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
const SET_SELECTED_ORGANIZATION = 'SET_SELECTED_ORGANIZATION';
const SET_SELECTED_DEPARTMENTS = 'SET_SELECTED_DEPARTMENTS';

const FETCH_USERS = 'FETCH_USERS';
const FETCH_ORGANIZATIONS = 'FETCH_ORGANIZATIONS';
const FETCH_WORKFLOW_TEMPLATES = 'FETCH_WORKFLOW_TEMPLATES';
const FETCH_EVENTS = 'FETCH_EVENTS';
const FETCH_LATEST_EVENTS = 'FETCH_LATEST_EVENTS';
const FETCH_DASHBOARDS = 'FETCH_DASHBOARDS';
const FETCH_REPORTS = 'FETCH_REPORTS';

const FETCH_SOWS = 'FETCH_SOWS';
const SET_SELECTED_SOW = 'SET_SELECTED_SOW';
const SET_SOW_FILE_URL = 'SET_SOW_FILE_URL';

const FETCH_PROJECTS = 'FETCH_PROJECTS';
const EDIT_PROJECT = 'EDIT_PROJECT';
const REMOVE_PROJECT = 'REMOVE_PROJECT';

const SET_POPUP = 'SET_POPUP';

const CREATE_WTD = 'CREATE_WTD';
const UPDATE_WTD = 'UPDATE_WTD';

const CREATE_META_SYSTEM = 'CREATE_META_SYSTEM';
const FETCH_META_SYSTEMS = 'FETCH_META_SYSTEMS';
const DELETE_META_SYSTEM = 'DELETE_META_SYSTEM';
const UPDATE_META_SYSTEM = 'UPDATE_META_SYSTEM';
const FETCH_META_SYSTEMS_FILTER = 'FETCH_META_SYSTEMS_FILTER';
const UPDATE_DELIVERABLES = 'UPDATE_DELIVERABLES';

const FETCH_SYSTEM_TRENDS = 'FETCH_SYSTEM_TRENDS';

export {
  SET_CURRENT_USER,
  SET_ACCESS_TOKEN,
  SET_REFRESH_TOKEN,
  SET_PASSWORD_RESET_TOKEN,
  SET_LOADING_STATUS,
  FETCH_USERS,
  FETCH_PROJECTS,
  FETCH_ORGANIZATIONS,
  FETCH_WORKFLOW_TEMPLATES,
  FETCH_EVENTS,
  FETCH_LATEST_EVENTS,
  FETCH_DASHBOARDS,
  FETCH_REPORTS,
  SET_POPUP,
  FETCH_SOWS,
  EDIT_PROJECT,
  REMOVE_PROJECT,
  SET_SELECTED_ORGANIZATION,
  SET_SELECTED_DEPARTMENTS,
  SET_SELECTED_SOW,
  SET_SOW_FILE_URL,
  CREATE_WTD,
  UPDATE_WTD,
  CREATE_META_SYSTEM,
  FETCH_META_SYSTEMS,
  DELETE_META_SYSTEM,
  UPDATE_META_SYSTEM,
  FETCH_SYSTEM_TRENDS,
  FETCH_META_SYSTEMS_FILTER,
  UPDATE_DELIVERABLES,
};
